### ISSUE TITLE
BUILD_SHARED_LIBS and ENABLE_SHARED_LIBS should be equiv

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#138]
double check when ever BUILD_SHARED_LIBS is set,  ENABLE_SHARED_LIBS is the same (and vice versa)

**Comment by white238** [comment]
Did you see a bug in relation to this? Kenny and I found one that BUILD_SHARED_LIBS/ENABLE_SHARED_LIBS were overriding the more granular SHARED blt_add_library option.  It currently is if BUILD_SHARED_LIBS is defined then use that for both the BUILD and ENABLE options otherwise it defaults to off.

This is kinda confusing maybe we should remove the ENABLE_SHARED_LIBS option.

**Comment by cyrush** [comment]
@mclarsen ran into this, it's also a big confusion for folks that use ccmake. 

I agree we should remove `ENABLE_SHARED_LIBS` option.

**Comment by cyrush** [comment]
fixed in #155
