### ISSUE TITLE
Option to get minimal BLT tree

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/blt#225]
I am using BLT in [this training repo](https://github.com/betterscientificsoftware/TrainingCi4Ecp). Using as a submodule wasn't the most attractive and so I opted to copy the whole thing.

It would be nice, however, to have a way to copy just the BLT CMake, Goolge Test, etc. functionality and not its

- travis, appveyer or other config files
- documentation
- tests
- examples

All those things are indeed small potatos but they don't have anything to do with my project and I nonethess wind up pushing them to my repo. I would rather they not be in the ``blt`` dir of my project. But, I am certainly not qualified to decide what should and should not be there to support all the functionality BLT is designed to support.

So, it would be nice to have the ability to get the *minimal* BLT tree.

**Comment by kennyweiss** [comment]
@markcmiller86 -- it looks like the ``export-ignore`` attribute in a ``.gitattributes`` file could be used, in conjunction with ``git-archive``.  (See: https://feeding.cloud.geek.nz/posts/excluding-files-from-git-archive )

I think the tricky part might be in devising a universal/acceptable set of files to include/exclude.  E.g. some users might want to exclude our included third-party libraries like ``gtest`` and ``gbenchmark``.

For your use case, there might be a way to write a custom ``git archive`` line that selects the desired files and directory that you're interested in? (e.g. https://stackoverflow.com/questions/1125476/retrieve-a-single-file-from-a-repository)

**Comment by kennyweiss** [comment]
You might be able to define a ``.gitattributes`` file in your repo and use it for the blt ``git archive`` command via the ``--worktree-attributes`` option -- https://stackoverflow.com/questions/42311670/specify-custom-gitattributes-file-location-for-git-archive

**Comment by cyrush** [comment]
@markcmiller86 we have talked about variations on this theme -- minifying to remove features (gtest source etc). In the grand scheme of things, I really think is more trouble than it's worth. Like Kenny said it boils down to how do we give folks enough control to exclude what they want. 

Maybe we could better list the things that are for our testing, etc -- I think it's a bit confusing to a new users.

**Comment by markcmiller86** [comment]
Yeah, so I am not so much asking to subset/minify on *features* that BLT is intended to provide to its consumers. I am just talking about removing those items that are specific to the BLT repo, tutorial, documentation, testing, etc., as opposed to those things BLT is intended to make available to its consumers. So, removing things like gtest, cmake, fruit or combinations thereof is not something I am asking for. 

In the modality where I copy the BLT repo, I get a slew of things that I do not need in order to *use* BLT in the way it was intended in my project. And, that extra stuff is just confusing to anyone who might be poking around my repo later. And, in the copy modality I describe here, I don't think any of the git-specific solutions proposed (e.g. ``.gitattributes``) will work anyways. 

So, maybe its something as simple as a script that, after someone copies the repo, the script goes through and removes the stuff that isn't essential to *using* BLT in the project it is copied into. I don't think that is such a big ask here. But, I understand if this isn't seen as a very high priority for BLT.

To help motivate this...I am using this in a non-LLNL, ECP project aimed at having working, documented, maintained hello-ecp-ci-world code examples which will involve several collaborators from other sites none of whom can we expect to have already experienced enough of the issues BLT solves to understand why its important. When they ask me what all the *stuff* is in that directory, I'd like to have a better answer than.... *Oh, you can ignore most of the stuff in there because it doesn't effect anything in the project.

It almost feels like what is currently considered BLT should actually be split into two parts; the BLT part that does all the important CMake, Gtest, Fruit, Sphinx, Doxygen, etc. magic (and is *the* thing that ges copied, submoduled, whatever around) and then one or more BLT example repos which document and demonstrate various modalities of its use within projects.

**Comment by white238** [comment]
My concern is the amount of effort and complexity this would add to BLT for little pay off.  The things you are asking to be removed are very small. I will run numbers tomorrow but it is all text files and small ones at that.  Maybe I am confused about what you are trying to avoid/achieve... maybe if we have a face to face about this it will make more sense.

**Comment by cyrush** [comment]
@markcmiller86 -- what we are doing is the basic practice of revision controlling the docs and testing logic right along side the product. 

I understand it seems funny in this case b/c it's directly included in another project, which makes it more visible.  But we don't bat an eye at this practice for TPLS. I also strongly feel this is a good practice. 


If folks as what all the stuff is -- I think its perfectly defensible to say that it includes logic for testing and documenting blt.  

Splitting into multiple repos would make the development process much more complex.  We want low development barriers.  Also there isn't just travis and appveyor testing, we are also doing bamboo testing. 

If we don't split repos -- we could write tests for a script that strips away things, but thats more maintenance, again I am not sure about cost vs benefit. 

All of that said, since you are copying in -- I think you can achieve what you want by using ``.gitingore`` with the right paths. That would be a simple solution where the mechanics are well known.  We wouldn't have to dangerously unfold several blades of the swiss army knife at the same time while trying to cut cardboard. 

Here is a suggested, but untested list:

```
blt/docs
blt/host-configs (although I think these are very useful to share ..)
blt/tests/internal
blt/.travis.yml
blt/appveyor.yml
```

The `.gitingore`` approach could go stale, you will have to be careful wen you update. But if you want a no hassle experience I think its best to just include everything, which we spend time to test.
