### ISSUE TITLE
Ability to specify the number of threads per core in blt_add_test

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#231]
The ``blt_add_test`` macro has a parameter to set the number of MPI ranks for the test (``NUM_MPI_TASKS``) but not a way to set the number of threads per core in openmp configurations.

Does anyone have ideas for a clean way to specify and apply the number of threads per core/rank?

For the former, we could add a new parameter, e.g. ``NUM_THREADS_PER_TASK`` or ``CPUS_PER_TASK`` (or something better).

For the latter, one approach might be to specify ``OMP_NUM_THREADS`` as a shell variable
e.g.
```bash
OMP_NUM_THREADS=4  ./foo            // non-mpi run
OMP_NUM_THREADS=4 srun -n4 ./foo    // mpi run
```

This would require prepending a string to the command.
Note: srun also has some options for specifying the number of cpus per task, but the approach that we take should work for mpi and non-mpi configurations.

Is anyone currently running openmp tests through ``blt_add_test`` ?

Credits: Thanks Ben Corbett for the suggestion.

**Comment by rhornung67** [comment]
@kennyweiss I run a lot of OpenMP stuff through blt_add_test in RAJA. I always set the OMP_NUM_THREADS environment variable. IMO, that's the easiest way to run tests with different numbers of threads.  But, I'm usually in the minority.

**Comment by kennyweiss** [comment]
Related to #2

**Comment by corbett5** [comment]
My initial implementation was adding something like this 
``` cmake
if ( ${arg_NUM_OMP_THREADS} )
        set(test_command  "/usr/bin/bash -c \"OMP_NUM_THREADS=${arg_NUM_OMP_THREADS}; ${test_command}\"")
endif()
```
to https://github.com/LLNL/blt/blob/b86d131ac1acc99f4aed7d710a8b5a9cf377d19e/cmake/BLTMacros.cmake#L712
But it was uglier than that since you need to edit the previous `test_command` slightly. I would post my code but I messed up the submodule and lost it.

While this worked the downsides were
1. The number of threads per task doesn't get passed to `MPIEXEC` so there's no guarantee the scheduler will provide each task with it's own set of threads.
2. It requires that `/usr/bin/bash` exist, which I don't believe is the case on Windows.
