### ISSUE TITLE
Guard executable locations 

### ISSUE THREAD

**Issue by ajpowelsnl** [LLNL/blt#545]
Hello -- We are developing RAJAPerf Suite as a test harness for Kokkos-Kernels and Kokkos.  Currently when we build the RAJAPerf Suite (RPS) executable (for Kokkos perf testing), we also build all executables for NON-RPS performance testing.  We would like to see ONLY the RPS executable in the bin directory.

We propose guarding the statements involved in generating  and placing the executables in the "SetupBLT.cmake" file, such that only our intended executable is generated and placed in bin:

```cmake
141     # Set the path where all the installed executables will go
142     set(CMAKE_RUNTIME_OUTPUT_DIRECTORY
143         ${PROJECT_BINARY_DIR}/bin
144         CACHE PATH
145         "Directory where executables will go in the build tree")
```
For more context, our intended executable, "tracked_testing" is accompanied by executables associated with native testing in Kokkos-Kernels:
```console
[ajpowel@kokkos-dev-2 build_merge_rps_infra]$ ls tpls/rajaperf/bin/
graph_color                      KokkosBlas_dot_perf_test          KokkosKernels_blas_serial    rajaperf_config.hpp   sparse_pcg                 sparse_sptrsv
graph_color_d2                   KokkosBlas_perf_test              KokkosKernels_common_openmp  RAJAPerf-fom.csv      sparse_spadd               sparse_sptrsv_cholmod
graph_mis_d2                     KokkosBlas_team_dot_perf_test     KokkosKernels_common_serial  RAJAPerf-kernels.csv  sparse_spgemm              sparse_sptrsv_superlu
KokkosBatched_Test_BlockJacobi   KokkosKernels_batched_dla_openmp  KokkosKernels_graph_openmp   RAJAPerf-speedup.csv  sparse_spgemm_jacobi       sparse_sptrsv_supernode
KokkosBatched_Test_BlockTridiag  KokkosKernels_batched_dla_serial  KokkosKernels_graph_serial   RAJAPerf-timing.csv   sparse_spiluk              tracked_testing
KokkosBlas2_gemv_perf_test       KokkosKernels_batched_sla_openmp  KokkosKernels_sparse_openmp  sparse_block_pcg      sparse_spmv
KokkosBlas3_gemm_perf_test       KokkosKernels_batched_sla_serial  KokkosKernels_sparse_serial  sparse_gs             sparse_spmv_struct
KokkosBlas3_perf_test            KokkosKernels_blas_openmp         RAJAPerf-checksum.txt        sparse_kk_spmv        sparse_spmv_struct_tuning
```

**Comment by white238** [comment]
I am not sure guarding this will get you the behavior you are looking for.  If this is uninitialized, CMake will put your executables scattered throughout your build directory based on your source's directory structure.

For example, an executable created in `unique/source/path/CMakeLists.txt` will end up in `<build dir>/unique/source/path`.

BLT defaults to `bin` because that is where most people expect their executables to be generated.  This variable is only used for an initial setting on executables and can be overrided on each target (info below), as well as by yourself overriding the global `CMAKE_RUNTIME_OUTPUT_DIRECTORY` after `SetupBLT.cmake` is included.

Most projects change the directory on executables that do not belong in that directory by setting `OUTPUT_DIR` on the `blt_add_executable` macro, like:

```
blt_add_executable(
   NAME some_test
   SOURCE some_test.cpp
   OUTPUT_DIR ${PROJECT_BINARY_DIR}/test)
```

This macro has a lot of built-in parameters that allow you to override default behavior in a single call. More info here:

https://llnl-blt.readthedocs.io/en/develop/api/target.html#blt-add-executable

**Comment by DavidPoliakoff** [comment]
Would `unset` do the job? w.r.t. `CMAKE_RUNTIME_OUTPUT_DIRECTORY` ?

**Comment by white238** [comment]
That took me a bit to figure out... You have to do this:

```
unset(CMAKE_RUNTIME_OUTPUT_DIRECTORY CACHE)
```

a straight `unset` doesn't do anything since it is a `CACHE` variable.

**Comment by white238** [comment]
Another suggestion is to create a macro for your examples/performance executables that wraps the `blt_add_exectuable` with the proper directory.  This can be useful for other reasons as well.  For example:

https://github.com/LLNL/serac/blob/4d252d110601bf837b502c16841e56b75a6cb209/cmake/SeracMacros.cmake#L143-L171

**Comment by ajpowelsnl** [comment]
Hi @white238 and @DavidPoliakoff -- Many thanks for this suggestion -- it sounds like just what we need.  I'll discuss tomorrow with David, and figure out a path forward.

**Comment by ajpowelsnl** [comment]
Hi Chris -- many thanks for your help!  Your suggested fix worked like a charm.  I really appreciate your help.
