### ISSUE TITLE
revisit use of USE_OPENMP and USE_MPI defines

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#7]
Since it is easy for users of BLT to add their own compiler defines for OpenMP or MPI targets, we wanted to discuss not adding them via blt_register_lib for openmp and mpi.

**Comment by gzagaris** [comment]
It makes more sense to me to let applications pass the corresponding macro definitions of their choice. That way BLT would be more flexible and not impose a naming convention. 

Also, for OpenMP specifically, there is also no need to pass a definition since the compiler would emit the `_OPENMP` definition, which to my knowledge is pretty standard.

**Comment by cyrush** [comment]
agreed about letting apps create their own defines -- these are definitely left over from Axom
