### ISSUE TITLE
consider blt macro that helps combine static libs

### ISSUE THREAD

**Issue by cyrush** [LLNL/blt#72]
there are a compelling cases for collapsing symbols from all TPLS and your lib into a single static lib to make it easy for consumers to link your app.

I believe Axom wants this, Alpine would use it as well. 

Details still to be worked out.

**Comment by cyrush** [comment]
Note: adding object lib support will help with this goal as well, but there are cases where object libs may not be practical:

* when using cuda
* when actually trying to re-package static TPLs

**Comment by zbeekman** [comment]
A note on object libs and Fortran:

Object libs can be useful for avoiding race conditions in Fortran builds. A Fortran source file that defines a module that is listed as a source file for more than one target, whose builds are not ordered due to dependencies, can trigger a race condition resulting in a build failure during parallel compilation. The CMake generated build system may overwrite/delete the .mod file from one thread of the build while the other one still needs it. The best work around for this is to create object libs for all source files that declare a Fortran module. This ensures that the .mod file and object file are only generated once and then reused for all targets.

I've reported this to CMake, and vaguely remember them telling me this is not a bug, although I'm not convinced.

**Comment by cyrush** [comment]
@zbeekman I have seen issues like this, but I didn't know the root cause. 
I always thought it was some issue with the compiler choosing colliding temporary names. 

Good to know that object libs avoids this issue.

**Comment by cyrush** [comment]
@zbeekman, do you have a bug report or a link to the thread about this to the CMake folks?

**Comment by zbeekman** [comment]
I asked again recently to confirm: https://gitlab.kitware.com/cmake/cmake/issues/17525

CMake's design is such that any source file that is listed as a part of multiple targets can expect to get recompiled for each target created through `add_library` or `add_executable`. 

Here is the discussion, feel free to weigh in: https://gitlab.kitware.com/cmake/cmake/issues/17525

**Comment by cyrush** [comment]
@zbeekman thanks, good to get a (more) complete understanding of the issue!

**Comment by rrsettgast** [comment]
@cyrush did that combine_static_libs macro take care of this?

**Comment by white238** [comment]
This can be solved with object libraries.
